#!/usr/bin/env python

import sys

import ProcHandlers

PBR = ProcHandlers.PBR

if len(sys.argv) > 1:
    symfile = sys.argv[1]
else:
    symfile = "/proc/self/exe"

slink = PBR.SymLinkFile
act = slink(symfile)

for result in act:
    print "Highlight({result})".format(result=result)
    print act.field
