#!/usr/bin/env python

import ProcHandlers

PBR = ProcHandlers.PBR
PFC = ProcHandlers.PFC

PREFIX = PBR.PREFIX_VAL
SUFFIX = PBR.SUFFIX_VAL
CONV = PBR.CONVERSION
NAME = PBR.FIELD_NAME
BEFORE = PBR.BEFORE_VAL

handler = PBR.TaggedMultiLineFile

REGISTER_FILE = PBR.register_file
REGISTER_PARTIAL_FILE = PBR.register_partial_file

#act = handler("/tmp/ps/status")
#act = handler("/tmp/ps/short-status")
act = handler("/proc/self/status")
#act = handler()

PBR.add_parse_rule(act, { PREFIX: "Name:\t", NAME: PFC.F_PROG_NAME } )
PBR.add_parse_rule(act, { PREFIX: "State:\t", NAME: PFC.F_RUNSTATUS } )
PBR.add_parse_rule(act, { PREFIX: "Tgid:\t", NAME: PFC.F_THREAD_GID, CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "Pid:\t", NAME: PFC.F_GID, CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "PPid:\t", NAME: PFC.F_PPID, CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "TracerPid:\t", NAME: PFC.F_TRACER_PID, CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "Uid:\t", NAME: PFC.F_UID_SET } )
PBR.add_parse_rule(act, { PREFIX: "Gid:\t", NAME: PFC.F_GID_SET } )
PBR.add_parse_rule(act, { PREFIX: "FDSize:\t", NAME: PFC.F_FDSIZE, CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "Groups:\t", NAME: PFC.F_GROUPS } )
PBR.add_parse_rule(act, { PREFIX: "VmPeak:\t", NAME: PFC.F_VM_PEAK, SUFFIX: " kB", CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "VmSize:\t", NAME: PFC.F_VM_SIZE, SUFFIX: " kB", CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "VmLck:\t", NAME: PFC.F_VM_LOCK, SUFFIX: " kB", CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "VmPin:\t", NAME: PFC.F_VM_PIN, SUFFIX: " kB", CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "VmHWM:\t", NAME: PFC.F_VM_HWM, SUFFIX: " kB", CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "VmRSS:\t", NAME: PFC.F_VM_RSS, SUFFIX: " kB", CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "VmData:\t", NAME: PFC.F_VM_DATA, SUFFIX: " kB", CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "VmStk:\t", NAME: PFC.F_VM_STACK, SUFFIX: " kB", CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "VmExe:\t", NAME: PFC.F_VM_EXE, SUFFIX: " kB", CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "VmLib:\t", NAME: PFC.F_VM_LIB, SUFFIX: " kB", CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "VmPTE:\t", NAME: PFC.F_VM_PTE, SUFFIX: " kB", CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "VmSwap:\t", NAME: PFC.F_VM_SWAP, SUFFIX: " kB", CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "Threads:\t", NAME: PFC.F_THREADS, CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "SigQ:\t", NAME: PFC.F_SIG_QUEUE } )
PBR.add_parse_rule(act, { PREFIX: "SigPnd:\t", NAME: PFC.F_SIG_PEND } )
PBR.add_parse_rule(act, { PREFIX: "ShdPnd:\t", NAME: PFC.F_SIG_SH_PEND } )
PBR.add_parse_rule(act, { PREFIX: "SigBlk:\t", NAME: PFC.F_SIG_BLOCK } )
PBR.add_parse_rule(act, { PREFIX: "SigIgn:\t", NAME: PFC.F_SIG_IGN } )
PBR.add_parse_rule(act, { PREFIX: "SigCgt:\t", NAME: PFC.F_SIG_CAUGHT } )
PBR.add_parse_rule(act, { PREFIX: "CapInh:\t", NAME: PFC.F_CAP_INHERIT } )
PBR.add_parse_rule(act, { PREFIX: "CapPrm:\t", NAME: PFC.F_CAP_PERM } )
PBR.add_parse_rule(act, { PREFIX: "CapEff:\t", NAME: PFC.F_CAP_EFF } )
PBR.add_parse_rule(act, { PREFIX: "CapBnd:\t", NAME: PFC.F_CAP_BSET } )
PBR.add_parse_rule(act, { PREFIX: "Cpus_allowed:\t", NAME: PFC.F_CPU_ALLOW_MASK } )
PBR.add_parse_rule(act, { PREFIX: "Cpus_allowed_list:\t", NAME: PFC.F_CPU_ALLOW_LIST } )
PBR.add_parse_rule(act, { PREFIX: "Mems_allowed:\t", NAME: PFC.F_MEM_ALLOW_MASK } )
PBR.add_parse_rule(act, { PREFIX: "Mems_allowed_list:\t", NAME: PFC.F_MEM_ALLOW_LIST } )
PBR.add_parse_rule(act, { PREFIX: "voluntary_ctxt_switches:\t", NAME: PFC.F_CSWITCH_VOL, CONV: long } )
PBR.add_parse_rule(act, { PREFIX: "nonvoluntary_ctxt_switches:\t", NAME: PFC.F_CSWITCH_NONVOL, CONV: long } )

act.add_eor_rule( "nonvoluntary_ctxt_switches", { BEFORE: ":" } )

for xx in act:
    print "- - -"
    for key in xx:
        print "{key}: '{val}' {vt}".format(key=key, val=str(xx[key]), vt=type(xx[key]).__name__)


class ProcSelfSTATUS(PBR.TaggedMultiLineFile):
    """Parse contents of process specific 'status' file, ex: /proc/self/status"""

    def extra_init(self, *opts):
        self.minfields = 2
        
        PBR.add_parse_rule(act, { PREFIX: "Name:\t", NAME: PFC.F_PROG_NAME } )
        PBR.add_parse_rule(act, { PREFIX: "State:\t", NAME: PFC.F_RUNSTATUS } )
        PBR.add_parse_rule(act, { PREFIX: "Tgid:\t", NAME: PFC.F_THREAD_GID, CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "Pid:\t", NAME: PFC.F_GID, CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "PPid:\t", NAME: PFC.F_PPID, CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "TracerPid:\t", NAME: PFC.F_TRACER_PID, CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "Uid:\t", NAME: PFC.F_UID_SET } )
        PBR.add_parse_rule(act, { PREFIX: "Gid:\t", NAME: PFC.F_GID_SET } )
        PBR.add_parse_rule(act, { PREFIX: "FDSize:\t", NAME: PFC.F_FDSIZE, CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "Groups:\t", NAME: PFC.F_GROUPS } )
        PBR.add_parse_rule(act, { PREFIX: "VmPeak:\t", NAME: PFC.F_VM_PEAK, SUFFIX: " kB", CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "VmSize:\t", NAME: PFC.F_VM_SIZE, SUFFIX: " kB", CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "VmLck:\t", NAME: PFC.F_VM_LOCK, SUFFIX: " kB", CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "VmPin:\t", NAME: PFC.F_VM_PIN, SUFFIX: " kB", CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "VmHWM:\t", NAME: PFC.F_VM_HWM, SUFFIX: " kB", CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "VmRSS:\t", NAME: PFC.F_VM_RSS, SUFFIX: " kB", CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "VmData:\t", NAME: PFC.F_VM_DATA, SUFFIX: " kB", CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "VmStk:\t", NAME: PFC.F_VM_STACK, SUFFIX: " kB", CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "VmExe:\t", NAME: PFC.F_VM_EXE, SUFFIX: " kB", CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "VmLib:\t", NAME: PFC.F_VM_LIB, SUFFIX: " kB", CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "VmPTE:\t", NAME: PFC.F_VM_PTE, SUFFIX: " kB", CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "VmSwap:\t", NAME: PFC.F_VM_SWAP, SUFFIX: " kB", CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "Threads:\t", NAME: PFC.F_THREADS, CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "SigQ:\t", NAME: PFC.F_SIG_QUEUE } )
        PBR.add_parse_rule(act, { PREFIX: "SigPnd:\t", NAME: PFC.F_SIG_PEND } )
        PBR.add_parse_rule(act, { PREFIX: "ShdPnd:\t", NAME: PFC.F_SIG_SH_PEND } )
        PBR.add_parse_rule(act, { PREFIX: "SigBlk:\t", NAME: PFC.F_SIG_BLOCK } )
        PBR.add_parse_rule(act, { PREFIX: "SigIgn:\t", NAME: PFC.F_SIG_IGN } )
        PBR.add_parse_rule(act, { PREFIX: "SigCgt:\t", NAME: PFC.F_SIG_CAUGHT } )
        PBR.add_parse_rule(act, { PREFIX: "CapInh:\t", NAME: PFC.F_CAP_INHERIT } )
        PBR.add_parse_rule(act, { PREFIX: "CapPrm:\t", NAME: PFC.F_CAP_PERM } )
        PBR.add_parse_rule(act, { PREFIX: "CapEff:\t", NAME: PFC.F_CAP_EFF } )
        PBR.add_parse_rule(act, { PREFIX: "CapBnd:\t", NAME: PFC.F_CAP_BSET } )
        PBR.add_parse_rule(act, { PREFIX: "Cpus_allowed:\t", NAME: PFC.F_CPU_ALLOW_MASK } )
        PBR.add_parse_rule(act, { PREFIX: "Cpus_allowed_list:\t", NAME: PFC.F_CPU_ALLOW_LIST } )
        PBR.add_parse_rule(act, { PREFIX: "Mems_allowed:\t", NAME: PFC.F_MEM_ALLOW_MASK } )
        PBR.add_parse_rule(act, { PREFIX: "Mems_allowed_list:\t", NAME: PFC.F_MEM_ALLOW_LIST } )
        PBR.add_parse_rule(act, { PREFIX: "voluntary_ctxt_switches:\t", NAME: PFC.F_CSWITCH_VOL, CONV: long } )
        PBR.add_parse_rule(act, { PREFIX: "nonvoluntary_ctxt_switches:\t", NAME: PFC.F_CSWITCH_NONVOL, CONV: long } )

        return


    def extra_next(self, sio):

        try:
            __split = self.field[PFC.F_UID_SET].split("\t")
            print "dbg:: Found {nn} uid values".format(nn=len(__split))
        except KeyError:
            print "dbg:: Err: No uid list"

        try:
            __split = self.field[PFC.F_GID_SET].split("\t")
            print "dbg:: Found {nn} gid values".format(nn=len(__split))
        except KeyError:
            print "dbg:: Err: No gid list"

        return self.field

REGISTER_FILE("/proc/self/status", ProcSelfSTATUS)
REGISTER_PARTIAL_FILE("status", ProcSelfSTATUS)
