#!/bin/bash

if [ "$1" = "" ]
then
	INSTALL_DIR="/usr/local/bin/"
else
	INSTALL_DIR="$1"
fi

rsync -avnu --no-owner --exclude COPYING --exclude .git --exclude .gitignore --exclude TEST \
  --exclude \*.pyc --exclude README.\* --exclude proc-file-\* --exclude .pylintrc --exclude install-PyProc\* \
  . "${INSTALL_DIR}"
