#!/bin/bash

INSTALL_DIR="/usr/local/bin/"

rsync -avnu --no-owner --exclude COPYING --exclude .git --exclude .gitignore --exclude TEST \
  --exclude \*.pyc --exclude README.\* --exclude proc-file-\* --exclude .pylintrc --exclude install-PyProc\* \
  . "${INSTALL_DIR}"
