#!/usr/bin/env python
"""Convert logical records from the indicated /proc/net file to JSON format"""

import sys
import ProcHandlers
import json
    
if sys.platform == "darwin":
    print "MacOS doesn't have a '/proc' filesystem, quitting."
    sys.exit(0)

QUALIFY = ""


if len(sys.argv) > 1:
    TARGET = sys.argv[1]
else:
    TARGET = "/proc/net/tcp"

HANDLER = ProcHandlers.GET_HANDLER(TARGET)

ACTIVE = HANDLER(TARGET)

REC = 0
FIELD_LIST = dict()
FIELD_LIST[0] = { 'source' : TARGET }

for srec in ACTIVE:
    if len(ACTIVE.field) > 0:
        REC += 1
        FIELD_LIST[REC] = dict()
        for fname in ACTIVE.field:
            FIELD_LIST[REC][fname] = ACTIVE.field[fname]

print json.dumps(FIELD_LIST, sort_keys=True, indent=4, separators=(',', ': '))
