#!/usr/bin/env python
"""Convert logical records from the indicated /proc/net file to a CSV file

"""

import sys
import ProcSysInfo
    
if sys.platform == "darwin":
    print "MacOS doesn't have a '/proc' filesystem, quitting."
    sys.exit(0)

qualify = ""

if len(sys.argv) > 1:
    target = sys.argv[1]
    if len(sys.argv) > 2:
        qualify = sys.argv[2]
else:
    target = "tcp"

seq = 0
sep = "|"

handler = ProcSysInfo.GetProcFileHandler(target)

if qualify != "":
    active = handler(qualify)
else:
    active = handler()

if qualify != "":
   target = target + "/" + qualify

for srec in active:
    out = ""
    seq = seq + 1

    if seq == 1:
        for key in active.field:
            out = out + sep + key
        print "{0:s}{1:s}".format(target, out)
        out = ""

    if len(active.field) > 0:
        for key in active.field:
            out = out + sep + str(active.field[key])
        print "{0:d}{1:s}".format(seq, out)
