#!/usr/bin/env python
"""Show the handler routine for the indicated /proc/net file, if there is one

"""

import sys
import ProcHandlers
    
if sys.platform == "darwin":
    print "MacOS doesn't have a '/proc' filesystem, quitting."
    sys.exit(0)

qualify = ""

if len(sys.argv) > 1:
    target = sys.argv[1]
    if len(sys.argv) > 2:
        qualify = sys.argv[2]
else:
    target = "tcp"

if target == "all":

    ProcHandlers.ShowProcFileHandlers()

else:

    handler = ProcHandlers.GetProcFileHandler(target)

    if qualify != "":
        active = handler(qualify)
    else:
        active = handler(target)

    if qualify != "":
        target = "{dir}/{file}".format(dir=target, file=qualify)

    print "File {0:s} handled by {1:s}".format(target, handler)

