#!/usr/bin/env python
"""
Show the handler routine for the indicated /proc/net file, if there is one
"""

import sys
import ProcHandlers

PBR = ProcHandlers.PBR
    
if sys.platform == "darwin":
    print "MacOS doesn't have a '/proc' filesystem, quitting."
    sys.exit(0)

QUALIFY = ""

if len(sys.argv) > 1:
    TARGET = sys.argv[1]
    if len(sys.argv) > 2:
        QUALIFY = sys.argv[2]
else:
    TARGET = "tcp"

if TARGET == "all":

    PBR.show_proc_file_handlers()

else:

    HANDLER = ProcHandlers.GET_HANDLER(TARGET)

    if QUALIFY != "":
        ACTIVE = HANDLER(QUALIFY)
    else:
        ACTIVE = HANDLER(TARGET)

    if QUALIFY != "":
        TARGET = "{dir}/{file}".format(dir=TARGET, file=QUALIFY)

    print "File {file} handled by {name:s} from {mod}".format(file=TARGET,
            name=HANDLER.__name__, mod=HANDLER.__module__)

