#!/usr/bin/env python

"""Lookup the recreator method for the given file"""

import ProcHandlers as PH
import sys
from regentest import *
import regentest as RG

# ---

PFC = PH.ProcFieldConstants

# ---

NOFUNC = 0

if len(sys.argv) > 1:
    TARGET = sys.argv[1]
else:
    TARGET = "/proc/net/tcp6"

if len(sys.argv) > 2:
    CNAME = sys.argv[2]
else:
    CNAME = TARGET

HANDLER = PH.GET_HANDLER(CNAME)
try:
    RECREATOR = str(RG.RECREATOR[HANDLER]).split()[1]
    print "{rec:s} recreates {inp:s}".format(inp=TARGET, rec=RECREATOR)
except KeyError:
    print "N/A recreates {inp:s}".format(inp=TARGET)
