#!/usr/bin/env python
"""Show the handler routine for the indicated /proc/net file, if there is one

"""

import sys
import ProcSysInfo
    
if sys.platform == "darwin":
    print "MacOS doesn't have a '/proc' filesystem, quitting."
    sys.exit(0)

qualify = ""

if len(sys.argv) > 1:
    target = sys.argv[1]
    if len(sys.argv) > 2:
        qualify = sys.argv[2]
else:
    target = "tcp"

seq = 0

handler = ProcSysInfo.GetProcFileHandler(target)

if qualify != "":
    active = handler(qualify)
else:
    active = handler()

if qualify != "":
    target = target + "/" + qualify

print "File {0:s} handled by {1:s}".format(target, handler)

