#!/usr/bin/env python
"""
Show the primary data file associated with the given handler name
"""

import sys
import ProcHandlers

PBR = ProcHandlers.PBR

NOT_FOUND = "N/A"

if sys.platform == "darwin":
    print "MacOS doesn't have a '/proc' filesystem, quitting."
    sys.exit(0)

if len(sys.argv) > 1:
    HANDLER = sys.argv[1]
else:
    HANDLER = "ProcNetTCP"

PRIMARY = NOT_FOUND

REG = PBR.get_file_registry()

for datafile in REG:
    if PRIMARY == NOT_FOUND:
        if REG[datafile].__name__ == HANDLER:
            PRIMARY = datafile

print "Handler {code} parses {file}".format(code=HANDLER, file=PRIMARY)

