#!/bin/bash

codelist=( $(./ShowProcHandler all \
    | gawk '$1 == "For" && !/ProcNetNULL/ { print $4; }')
)

# ---

typeset -i seq total

total="${#codelist[@]}"
seq=1

# ---

for handler in ${codelist[@]}
do
	echo "[${seq}/${total}] $(./verify-handler ${handler})"
	seq=$(( ${seq} + 1 ))
done
